const itemDb = {
    0: {
        itemName: "Black Cat",
        itemPath: "assets/gfx/cat/catBlack.json",
        itemWorth: 36,
        itemThumb: "assets/img/small/catBlack.png",
        itemChance: 0.1,
        itemRarity: "uncommon",
    },
    1: {
        itemName: "White Striped Cat",
        itemPath: "assets/gfx/cat/catBlackWhite.json",
        itemWorth: 36,
        itemThumb: "assets/img/small/catWhiteBlack.png",
        itemChance: 0.1,
        itemRarity: "uncommon",
    },
    2: {
        itemName: "Orange cat",
        itemPath: "assets/gfx/cat/catA.json",
        itemWorth: 36,
        itemThumb: "assets/img/small/catA.png",
        itemChance: 0.1,
        itemRarity: "uncommon",
    },
    3: {
        itemName: "Poison Flask",
        itemPath: "assets/gfx/obj/poison.json",
        itemWorth: 9,
        itemThumb: "assets/img/small/poison.png",
        itemChance: 0.5,
        itemRarity: "common",
    },
    4: {
        itemName: "Blue Cat",
        itemPath: "assets/gfx/cat/catBlue.json",
        itemWorth: 91,
        itemThumb: "assets/img/small/catBlue.png",
        itemChance: 0.05,
        itemRarity: "rare",
    },
    5: {
        itemName: "Octocat",
        itemPath: "assets/gfx/cat/octoCat.json",
        itemWorth: 96,
        itemThumb: "assets/img/small/octoCat.png",
        itemChance: 0.045,
        itemRarity: "rare",
    },
    6: {
        itemName: "Lucky Cat",
        itemPath: "assets/gfx/cat/luckyCat.json",
        itemWorth: 8888,
        itemThumb: "assets/img/small/luckyCat.png",
        itemChance: 0.005,
        itemRarity: "mythic",
    },
    7: {
        itemName: "Meowth",
        itemPath: "assets/gfx/cat/meowth.json",
        itemWorth: 91,
        itemThumb: "assets/img/small/meowth.png",
        itemChance: 0.05,
        itemRarity: "rare",
    },
    8: {
        itemName: "Polite Cat",
        itemPath: "assets/gfx/cat/catPolite.json",
        itemWorth: 91,
        itemThumb: "assets/img/small/catPolite.png",
        itemChance: 0.05,
        itemRarity: "rare",
    },
};
